# -*- mode: ruby -*-
# vi: set ft=ruby :

$script_all = <<SCRIPT
yum -y install vim tree
ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
source ~/.bashrc
cat /dev/null > ~/.bash_history
bash /root/hname.sh
SCRIPT

$script1 = <<SCRIPT
yum -y install epel-release
yum -y install ansible
cat /dev/null > ~/.bash_history
bash /root/sshid.sh
SCRIPT

Vagrant.configure("2") do |config|
    config.ssh.username = 'root'
    config.ssh.password = 'vagrant'
    config.ssh.insert_key = 'true'
    config.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
    end

    config.vm.define "elk2" do |app|
      app.vm.box = "centos_tmp"
      app.vm.hostname = "elk2"
      app.vm.provision "file", source: ".bashrc",destination: "/root/"
      app.vm.provision "file", source: "hname.sh",destination: "/root/"
      app.vm.provision "shell", inline: $script_all
      app.vm.network :private_network, ip: "192.168.60.102"
    end

    config.vm.define "elk3" do |app|
      app.vm.box = "centos_tmp"
      app.vm.hostname = "elk3"
      app.vm.provision "file", source: ".bashrc",destination: "/root/"
      app.vm.provision "file", source: "hname.sh",destination: "/root/"
      app.vm.provision "shell", inline: $script_all
      app.vm.network :private_network, ip: "192.168.60.103"
    end

    config.vm.define "elk1" do |app|
      app.vm.box = "centos_tmp"
      app.vm.hostname = "elk1"
      app.vm.provision "file", source: "hosts",destination: "/etc/ansible/hosts"
      app.vm.provision "file", source: ".bashrc",destination: "/root/"
      app.vm.provision "file", source: "hname.sh",destination: "/root/"
      app.vm.provision "file", source: "sshid.sh",destination: "/root/"
      app.vm.provision "shell", inline: $script_all
      app.vm.provision "shell", inline: $script1
      app.vm.network :private_network, ip: "192.168.60.101"
    end
end