version: '3.4'
services:
  prometheus:
    image: prom/prometheus:v2.20.0
    restart: always
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /opt/docker/prometheus/data:/prometheus   #prometheus数据目录
      - /opt/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml   #prometheus配置文件
      - /opt/docker/prometheus/rules.yml:/etc/prometheus/rules.yml   #报警配置文件
    #设置启动选项，指定配置文件位置，指定存储路径，指定数据保留天数（默认15天），指定最大数据量（默认不限制）,指定热更新
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --storage.tsdb.retention.time=3d --storage.tsdb.retention.size=50GB --web.enable-lifecycle
