version: '3' 
services:  
  nacos1:
    image: nacos/nacos-server:2.0.1
    container_name: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    restart: always
    privileged: true
    environment:
      #如果支持主机名可以使用hostname,否则使用ip，默认也是ip
      PREFER_HOST_MODE: 10.1.2.3
      #数据源平台 仅支持mysql或不保存empty
      SPRING_DATASOURCE_PLATFORM: mysql 
      #一般是本机的IP地址
      NACOS_SERVER_IP: 10.1.2.3
      #集群中其它节点[ip1:port ip2:port ip3:port]
      NACOS_SERVERS: 10.1.2.1:8848 10.1.2.2:8848 10.1.2.3:8848  
      #mysql配置
      MYSQL_SERVICE_HOST: 10.1.2.1  
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: abc2021
      #JVM调优参数
      JVM_XMS: 256m
      JVM_XMX: 256m
      JVM_XMN: 256m
    
    volumes:
      - ./cluster-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties