version: '3.1'
services:
  zoo1:
    image: zookeeper:3.6.2
    restart: always
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=${ZK2}:2888:3888;2181 server.3=${ZK3}:2888:3888;2181
      TZ: "Asia/Shanghai"
    env_file:
      - ./.zkenv