version: '3.1'
services:
  zoo1:
    image: zookeeper:3.6.2
    restart: always
    container_name: zookeeper
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    environment:
      ZOO_MY_ID: 1
      #ZOOKEEPER_CLIENT_PORT: 2181
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=172.16.46.2:2888:3888;2181 server.3=172.16.46.3:2888:3888;2181
      #ZOO_STANDALONE_ENABLED: "false"
      TZ: "Asia/Shanghai"
