#文件内容
version: '3.4'

services:
  kafka:
    image: wurstmeister/kafka
    restart: always
    #根据机器修改
    hostname: 172.40.200.10
    container_name: kafka
    ports:
    - 9092:9092
    environment:
      #根据机器修改
      KAFKA_ADVERTISED_HOST_NAME: 172.40.200.10
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: 172.40.200.10:2181,172.20.200.20:2181,172.40.200.30:2181
    volumes:
    - /opt/docker/kafka/data:/kafka

