version: '3.5'
services:
 zabbix-mysql:
  image: mysql:8.0
  container_name: mysql
  # environment:
  #   - COMPOSE_PROJECT_NAME=zabbix
  ports:
    - "3306:3306"
    - "33060:33060"
  restart: always
  command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin, --lower_case_table_names=1, --innodb_use_native_aio=0,--default-authentication-plugin=mysql_native_password]
  cap_add:
    - SYS_NICE  # CAP_SYS_NICE   ##mbind: Operation not permitted
  volumes:
   - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw
  env_file:
   - .env/.env_db_mysql
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
   - MYSQL_ROOT_PASSWORD
  user: root
  stop_grace_period: 1m

#  db_data_mysql:
#   image: busybox
#   volumes:
#    - ./zbx_env/var/lib/mysql:/var/lib/mysql:rw

secrets:
  MYSQL_USER:
    file: .mysql/.MYSQL_USER
  MYSQL_PASSWORD:
    file: .mysql/.MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: .mysql/.MYSQL_ROOT_PASSWORD