version: '3.5'
services:
 zabbix-javagate:
  image: zabbix/zabbix-java-gateway:alpine-4.4-latest
  container_name: java-gateway
  # environment:
  #   - COMPOSE_PROJECT_NAME=zabbix
  ports:
   - "10052:10052"
  restart: always
  # deploy:
  #  resources:
  #   limits:
  #     cpus: '0.5'
  #     memory: 512M
  #   reservations:
  #     cpus: '0.25'
  #     memory: 256M
  env_file:
   - .env/.env_java
  user: root
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix Java Gateway"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "java-gateway"
   com.zabbix.os: "alpine"