version: '3.5'
services:
 zabbix-snmptraps:
  image: zabbix/zabbix-snmptraps:alpine-4.4-latest
  container_name: snmptraps
  # environment:
  #   - COMPOSE_PROJECT_NAME=zabbix
  ports:
   - "162:162/udp"
  restart: always
  volumes:
   - ./zbx_env/var/lib/zabbix/snmptraps:/var/lib/zabbix/snmptraps:rw
  # deploy:
  #  resources:
  #   limits:
  #     cpus: '0.5'
  #     memory: 256M
  #   reservations:
  #     cpus: '0.25'
  #     memory: 128M
  user: root
  stop_grace_period: 5s
  labels:
   com.zabbix.description: "Zabbix snmptraps"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "snmptraps"
   com.zabbix.os: "alpine"