version: '3.5'  
services:  
#    db:  
#      image: docker.io/mysql:latest  
#      volumes:  
#        - /mysql/datadir_tomcat:/var/lib/mysql  
#        - /mysql/conf:/etc/mysql/conf.d:ro  
#      restart: always  
#      environment:  
#        MYSQL_ROOT_PASSWORD: password  

  zabbix-tomcat01:  
    #  depends_on:  
    #    - db  
     image: docker.io/tomcat:latest  
     container_name: tomcat1
    #  environment:
    #   - COMPOSE_PROJECT_NAME=zabbix
     volumes:  
       - ./pmt_tomcat/tomcat01/webapps:/usr/local/tomcat/webapps  
    #  links:  
    #    - db:db  
     ports:  
       - "8081:8080"  
     restart: always  

  zabbix-tomcat02:  
    #  depends_on:  
    #    - db  
     image: docker.io/tomcat:latest  
     container_name: tomcat2
    #  environment:
    #   - COMPOSE_PROJECT_NAME=zabbix
     volumes:  
       - ./pmt_tomcat/tomcat02/webapps:/usr/local/tomcat/webapps  
    #  links:  
    #    - db:db  
    #    - tomcat01:tomcat01  
     ports:  
       - "8082:8080"  
     restart: always