# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    (1..3).each do |i|
      config.vm.define "nginx#{i}" do |node|
        node.vm.box = "centos_tmp"
        node.vm.box_check_update = false
        node.vm.hostname = "nginx#{i}"
        node.vm.network "private_network", ip: "192.168.60.10#{i}"
        node.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "3072", "--cpus", "2"]
        end
      end
    end
  end