version: '2.0'
services:
  nginx:
    image: nginx:1.17.6
    container_name: nginx
    restart: always
    ports:
      - "80:9000"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      #- ./html/:/var/www/html/
      - ./ssl:/etc/nginx/ssl
      - ./conf.d:/etc/nginx/conf.d
    environment:
      - TZ=Asia/Shanghai
