global: 
  # 处理超时时间，默认为5min
  resolve_timeout: 5m 
  # 发送邮箱设置
  smtp_smarthost: 'smtp.163.com:25' 
  smtp_from: 'xx@163.com'
  smtp_auth_username: 'xx@163.com'
  smtp_auth_password: 'KSWIRLQGGYHHHGG'
  #wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/' # 企业微信地址

templates:
  - 'template/*.tmpl'

route:
  # 报警分组依据
  group_by: ['alertname']
  # 第一次等待多久时间发送一组警报的通知
  group_wait: 10s
  # 在发送新警报前的等待时间
  group_interval: 10s
  # 发送重复警报的周期 >= 2min,频率过高会被ISP禁用smtp服务；
  repeat_interval: 2m
  # 发送警报的接收者的名称，以下receivers name的名称
  receiver: 'default_email' 
  ## 一层
  routes:
  - match:
      severity: critical
    receiver: 'default_email'
    # 优先级高于父group_wait
    group_wait: 10s
    # 二层
    routes:        
    - receiver: 'team-Y-pager'
      match_re:
        service: '^(foo1|foo2|baz)$'
      # 三层
      routes:     
      - receiver: 'team-X-pager'
        match:
          owner: 'team-X'     
        continue: true
      - receiver: 'team-Y-pager'
        match:
          owner: 'team-Y' 

# 定义警报接收者信息
receivers:
- name: 'default_email'
  email_configs:
  - to : 'xx@163.com'
    send_resolved: true

- name: 'alert_email'
  email_configs:
  - to : 'xx@163.com'
    send_resolved: true

- name: 'team-X-pager'
  email_configs:
  - to: 'xx@163.com'
  # webhook_configs:                     
  # - url: 'http://127.0.0.1:5001/'  
    send_resolved: true

- name: 'team-Y-pager'
  # webhook_configs:                     
  # - url: 'http://127.0.0.1:5001/'
  email_configs:
  - to: 'yh713027@163.com'
    send_resolved: true
# receivers:
#   - name: 'default_email' # 警报
#     email_configs: # 邮箱配置
#     - to: 'auggieyang@163.com'  # 接收警报的email配置
      #html: '{{ template "test.html" . }}' # 设定邮箱的内容模板
      #headers: { Subject: "[WARN] 报警邮件"} # 接收邮件的标题
    #webhook_configs: # webhook配置
    #- url: 'http://127.0.0.1:5001'
    #send_resolved: true
    #wechat_configs: # 企业微信报警配置
    #- send_resolved: true
    #  to_party: '1' # 接收组的id
    #  agent_id: '1000002' # (企业微信-->自定应用-->AgentId)
    #  corp_id: '******' # 企业信息(我的企业-->CorpId[在底部])
    #  api_secret: '******' # 企业微信(企业微信-->自定应用-->Secret)
    #  message: '{{ template "test_wechat.html" . }}' # 发送消息模板的设定

# 一个inhibition规则是在与另一组匹配器匹配的警报存在的条件下，
# 使匹配一组匹配器的警报失效的规则。两个警报必须具有一组相同的标签。 
inhibit_rules: 
  - source_match: 
     severity: 'critical' 
    target_match: 
     severity: 'warning' 
    equal: ['alertname', 'instance']