global:
  # 默认抓取间隔, 15秒向目标抓取一次数据。
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    monitor: codelab-monitor   ##prometheus头标
rule_files:
  - "rules.yml"
scrape_configs:

- job_name: prometheus
  #重写默认抓取时间
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
  - targets:
    - 172.40.200.10:9100
    - 172.40.200.20:9100
    labels:
      group: client-node-exporter

- job_name: kafka-job
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 172.40.200.10:9308
    - 172.40.200.20:9308
    labels:
      group: kafka-node-exporter

- job_name: elk_job
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 172.40.200.10:9114
    labels:
      group: elk-node-exporter

- job_name: pg_job
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 172.10.0.3:9187
    labels:
      group: pg-node-exporter2

