global:
  # 默认抓取间隔, 15秒向目标抓取一次数据。
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    monitor: codelab-monitor
rule_files:
  - "rules.yml"   # 设置报警规则
scrape_configs:
- job_name: prometheus
  #重写默认抓取时间
  scrape_interval: 10s
  scrape_timeout: 10s
  #metrics数据查看前端访问地址
  metrics_path: /metrics
  scheme: http
  static_configs:
  #这个固定
  - targets:
    - localhost:9090
  #linux服务器监控，根据需求修改，需要先在对应机器上安装node-exporter
  - targets:
    - 172.40.200.10:9100
    - 172.40.200.20:9100
    - 172.40.200.30:9100
    - 172.40.210.10:9100
    - 172.10.0.6:9100
    labels:
      group: client-node-exporter
- job_name: kafka-job
  metrics_path: /metrics
  scheme: http
  static_configs:
  #kafka监控，根据需求修改，需要现在对应机器上安装kafka-exporter
  - targets:
    - 172.40.200.10:9308
    - 172.40.200.20:9308
    - 172.40.200.20:9308
    labels:
      group: kafka-node-exporter

- job_name: elk_job
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    #- 172.40.200.10:9114
    #- 172.40.200.20:9114
    labels:
      group: elk-node-exporter

- job_name: pg_job
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    #- 172.40.200.30:9187  #测试库
    - 172.10.0.3:9187     #生产库
    labels:
      group: pg-node-exporter2

