groups:
- name: rule__mem_50
  rules:
  - alert: "内存使用率大于50%报警"
    expr: 100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes) > 50
    for: 1s
    labels:
      severity: critical
    annotations:
      summary: "服务名:{{$labels.alertname}}"
      description: "内存使用率大于50% : {{ $value }}"
      value: "{{ $value }}"

- name: rule__mem_60
  rules:
  - alert: "内存使用率大于60%报警"
    expr: 100 - ((node_memory_MemAvailable_bytes * 100) / node_memory_MemTotal_bytes) > 60
    for: 1s
    labels:
      severity: warning
    annotations:
      summary: "服务名:{{$labels.alertname}}"
      description: "内存使用率大于60% : {{ $value }}"
      value: "{{ $value }}"

- name: rule__elk_heartbeat
  rules:
  - alert: "elk集群宕机"
    #expr: up{job="elk_job"} == 0
    expr: elasticsearch_cluster_health_up{job="elk_job"} == 0
    labels:
      severity: critical
    annotations:
      summary: "{{$labels.instance}}: has been down"
      description: "{{$labels.instance}}: job {{$labels.job}} has been down "
      value: "{{$value}}"

- name: rule__kafka_heartbeat
  rules:
  - alert: "kafka宕机"
    expr: kafka_brokers{job="kafka_job"} == 0
    labels:
      severity: critical
    annotations:
      summary: "{{$labels.instance}}: has been down"
      description: "{{$labels.instance}}: job {{$labels.job}} has been down "
      value: "{{$value}}"

- name: rule__disk_30
  rules:
  - alert: "硬盘使用率大于30"
    expr: 100 - (node_filesystem_free_bytes{mountpoint="/",fstype=~"ext4|xfs"} / node_filesystem_size_bytes{fstype=~"ext4|xfs"} * 100) > 30
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance  }} ：{{ $labels.mountpoint }} 分区使用率过高" 
      description: "{{ $labels.instance  }} ： {{ $labels.job  }} ：{{ $labels.mountpoint  }} 这个分区使用大于百分之30% (当前值：{{ $value }})"

- name: rule__disk_50
  rules:
  - alert: "硬盘使用率大于50"
    expr: 100 - (node_filesystem_free_bytes{mountpoint="/",fstype=~"ext4|xfs"} / node_filesystem_size_bytes{fstype=~"ext4|xfs"} * 100) > 50
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Instance {{ $labels.instance  }} ：{{ $labels.mountpoint }} 分区使用率过高" 
      description: "{{ $labels.instance  }} ： {{ $labels.job  }} ：{{ $labels.mountpoint  }} 这个分区使用大于百分之50% (当前值：{{ $value }})"