version: "3"
services:
  mysql:
    image: mysql:5.7.30
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Shanghai"
    ports:
      - 3306:3306
    volumes:
      # - /opt/docker/mysql/my.cnf:/etc/mysql/my.cnf
      - /opt/docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - /opt/docker/mysql/data:/var/lib/mysql