version: '3.7'
services:
  jenkins:
    #image: registry.cn-shanghai.aliyuncs.com/auggie/devops:jenkins_officially_plugin
    image: jenkins/jenkins:lts
    ports:
      - 8088:8080
      - 50000:50000
    container_name: jenkins
    ## 不设置privileged会导致无法手动升级Jenkins，也会导致Jenkins目录权限不够；
    privileged: true
    user: root
    volumes:
      - /opt/docker/jenkins/jenkins:/var/jenkins_home
      #- /opt/docker/jenkins/jenkins/m2:/root/.m2
      #- /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "assets-cdn.github.com:192.30.253.112"
      - "github.global.ssl.fastly.net:151.101.113.194"
    environment:
      #- CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml
      - JAVA_OPTS="-Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Shanghai"
      - TZ="Asia/Shanghai"