version: '3.5'
services:
 zabbix-nginxweb:
  image: zabbix/zabbix-web-nginx-mysql:alpine-4.4-latest
  container_name: nginxweb
  # environment:
  #   - COMPOSE_PROJECT_NAME=zabbix
  ports:
   - "80:80"
   - "8443:443"
  restart: always
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/timezone:/etc/timezone:ro
   - ./zbx_env/etc/ssl/nginx:/etc/ssl/nginx:ro
  # deploy:
  #  resources:
  #   limits:
  #     cpus: '0.70'
  #     memory: 512M
  #   reservations:
  #     cpus: '0.5'
  #     memory: 256M
  env_file:
   - .env/.env_db_mysql
   - .env/.env_web
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
  user: root
  healthcheck:
   test: ["CMD", "curl", "-f", "http://localhost"]
   interval: 10s
   timeout: 5s
   retries: 3
   start_period: 30s
  stop_grace_period: 10s
  sysctls:
   - net.core.somaxconn=65535
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with MySQL database support"
   com.zabbix.company: "Zabbix LLC"
   com.zabbix.component: "zabbix-frontend"
   com.zabbix.webserver: "nginx"
   com.zabbix.dbtype: "mysql"
   com.zabbix.os: "alpine"

secrets:
  MYSQL_USER:
    file: .mysql/.MYSQL_USER
  MYSQL_PASSWORD:
    file: .mysql/.MYSQL_PASSWORD