version: '2'
services:
  cass2:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - 7000:7000
      - 9042:9042
    volumes:
      - ./cassandra_data:/var/lib/cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra,cassandra2
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster2
      # - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_BROADCAST_ADDRESS=cassandra2
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack01
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_START_RPC=true
      - TZ="Asia/Shanghai"
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Therefore, memory options are mandatory if multiple Cassandras are launched in the same node.
      - MAX_HEAP_SIZE=1G
      - HEAP_NEWSIZE=200M
    restart: always
    extra_hosts:
      - "cassandra:192.168.60.101"
      - "cassandra2:192.168.60.102"