version: "3"
services:
  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        TZ: "Asia/Shanghai"
    ports:
        - 5432:5432
    volumes:
        - ./data/postgresql:/var/lib/postgresql/data